[package]
name = "rust_lib_project"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
bip39 = "2.0.0"
flutter_rust_bridge = "=2.0.0-dev.25"
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = {version="0.28.1",features=["hashes","rand"]}
