// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

String just({dynamic hint}) => RustLib.instance.api.just(hint: hint);

class UserKey {
  final Uint8List privateKey;

  const UserKey({
    required this.privateKey,
  });

  Future<String> generateSignature({required String message, dynamic hint}) =>
      RustLib.instance.api.userKeyGenerateSignature(
        that: this,
        message: message,
      );

  static Future<UserKey> newUserKey({required List<int> seed, dynamic hint}) =>
      RustLib.instance.api.userKeyNew(seed: seed, hint: hint);

  @override
  int get hashCode => privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserKey &&
          runtimeType == other.runtimeType &&
          privateKey == other.privateKey;
}
